# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class AddWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(697, 501)
        Dialog.setAccessibleName("")
        Dialog.setAccessibleDescription("")
        self.category = QtWidgets.QComboBox(Dialog)
        self.category.setGeometry(QtCore.QRect(30, 390, 641, 22))
        self.category.setObjectName("category")
        self.category.addItem("")
        self.category.addItem("")
        self.category.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 131, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 431, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 281, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 300, 171, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 370, 131, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(204, 440, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(374, 440, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 190, 641, 91))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(30, 40, 641, 41))
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(30, 120, 641, 31))
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(30, 320, 641, 31))
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.plainTextEdit_2.clear)
        self.pushButton.clicked.connect(self.plainTextEdit_3.clear)
        self.pushButton.clicked.connect(self.plainTextEdit.clear)
        self.pushButton.clicked.connect(self.plainTextEdit_4.clear)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Agregar"))
        self.category.setItemText(0, _translate("Dialog", "Comedia"))
        self.category.setItemText(1, _translate("Dialog", "Musical"))
        self.category.setItemText(2, _translate("Dialog", "Documental"))
        self.label.setText(_translate("Dialog", "Nombre de la Película"))
        self.label_2.setText(_translate("Dialog", "Duración de la Película (HH:MM:SS)"))
        self.label_3.setText(_translate("Dialog", "Descripción"))
        self.label_4.setText(_translate("Dialog", "Director"))
        self.label_5.setText(_translate("Dialog", "Categoría"))
        self.pushButton.setText(_translate("Dialog", "Borrar"))
        self.pushButton_2.setText(_translate("Dialog", "Agregar"))

    
